!pip install pymongo

In [1]:
import pymongo

In [6]:
# MongoDB 커넥션 연결
conn = pymongo.MongoClient("mongodb://id330:pw330@175.126.37.21:37017/db330")

# 데이터베이스 연결
db = conn.get_database('db330')

# 컬렉션(테이블) 연결/만들기
db.drop_collection('gdp_csv')
collection = db.get_collection('gdp_csv')

In [3]:
# 하둡의 csv 파일 읽기
import pandas as pd
from hdfs import InsecureClient
fs = InsecureClient('http://bdata.iptime.org:9999', user='hadoop')
# 1인당 gdp
path = '/user/hadoop/sports/'
f_name = '_20250110104927.csv'
with fs.read(f'{path}{f_name}', encoding='utf-8') as reader:
    df1 = pd.read_csv(reader)

df1

,시점,대한민국,중국,일본,미국,브라질,페루,핀란드,프랑스,독일,스웨덴,영국,남아프리카공화국,오스트레일리아
0,2001,4.7,8.3,0.4,1.0,1.4,0.6,2.6,2.0,1.7,1.4,2.6,2.7,2.0
1,2002,7.7,9.1,0.0,1.7,3.1,5.5,1.7,1.1,-0.2,2.2,1.8,3.7,4.0
2,2003,3.1,10.0,1.5,2.8,1.1,4.2,2.0,0.8,-0.7,2.3,3.1,2.9,3.1
3,2004,5.2,10.1,2.2,3.8,5.8,5.0,4.0,2.8,1.2,4.3,2.4,4.6,4.2
4,2005,4.4,11.4,1.8,3.5,3.2,6.3,2.8,1.7,0.7,2.9,2.7,5.3,3.2
5,2006,5.2,12.7,1.4,2.8,4.0,7.5,4.0,2.4,3.8,4.7,2.4,5.6,2.8
6,2007,5.8,14.2,1.5,2.0,6.1,8.5,5.3,2.4,3.0,3.4,2.6,5.4,3.8
7,2008,3.0,9.7,-1.2,0.1,5.1,9.1,0.8,0.3,1.0,-0.5,-0.2,3.2,3.6
8,2009,0.8,9.4,-5.7,-2.6,-0.1,1.1,-8.1,-2.9,-5.7,-4.3,-4.6,-1.5,1.9
9,2010,7.0,10.6,4.1,2.7,7.5,8.3,3.2,1.9,4.2,6.0,2.2,3.0,2.2
10,2011,3.7,9.6,0.0,1.6,4.0,6.3,2.5,2.2,3.9,3.2,1.1,3.2,2.4
11,2012,2.5,7.9,1.4,2.3,1.9,6.1,-1.4,0.3,0.4,-0.6,1.5,2.4,3.9
12,2013,3.3,7.8,2.0,2.1,3.0,5.9,-0.9,0.6,0.4,1.2,1.8,2.5,2.6
13,2014,3.2,7.4,0.3,2.5,0.5,2.4,-0.4,1.0,2.2,2.7,3.2,1.4,2.6
14,2015,2.9,7.0,1.6,2.9,-3.5,3.3,0.5,1.1,1.5,4.5,2.2,1.3,2.2
15,2016,3.2,6.8,0.8,1.8,-3.3,4.0,2.8,1.1,2.2,2.1,1.9,0.7,2.8
16,2017,3.4,6.9,1.7,2.5,1.3,2.5,3.2,2.3,2.7,2.6,2.7,1.2,2.3
17,2018,3.2,6.7,0.6,3.0,1.8,4.0,1.1,1.9,1.0,2.0,1.4,1.6,2.9
18,2019,2.3,6.0,-0.4,2.5,1.2,2.2,1.2,1.8,1.1,2.0,1.6,0.3,2.2
19,2020,-0.7,2.2,-4.1,-2.2,-3.3,-10.9,-2.4,-7.5,-3.8,-2.2,-10.4,-6.0,-0.3
20,2021,4.6,8.4,2.6,5.8,4.8,13.4,2.8,6.4,3.2,6.1,8.7,4.7,2.1
21,2022,2.7,3.0,1.0,1.9,3.0,2.7,1.3,2.5,1.8,2.7,4.3,1.9,4.3
22,2023,1.4,5.2,1.9,2.5,2.9,-0.6,-1.0,0.7,-0.3,-0.2,0.1,0.6,3.0

In [5]:
df1.rename(columns={"시점":"year", 
                    "대한민국":"korea", 
                    "중국":"china", 
                    "일본":"japan", 
                    "미국":"usa", 
                    "브라질":"brazil", 
                    "페루":"peru", 
                    "핀란드":"finland", 
                    "프랑스":"france", 
                    "독일":"germany", 
                    "스웨덴":"sweden", 
                    "영국":"england", 
                    "남아프리카공화국":"southAfrica", 
                    "오스트레일리아":"australia"
                   }, inplace=True)
df1.head(2)

,year,korea,china,japan,usa,brazil,peru,finland,france,germany,sweden,england,southAfrica,australia
0,2001,4.7,8.3,0.4,1.0,1.4,0.6,2.6,2.0,1.7,1.4,2.6,2.7,2.0
1,2002,7.7,9.1,0.0,1.7,3.1,5.5,1.7,1.1,-0.2,2.2,1.8,3.7,4.0

In [7]:
# 컬렉션에 DataFrame 형식 데이터 입력
collection.insert_many(df1.to_dict(orient='records'))

InsertManyResult([ObjectId('679193a47fd85c8616659c2b'), ObjectId('679193a47fd85c8616659c2c'), ObjectId('679193a47fd85c8616659c2d'), ObjectId('679193a47fd85c8616659c2e'), ObjectId('679193a47fd85c8616659c2f'), ObjectId('679193a47fd85c8616659c30'), ObjectId('679193a47fd85c8616659c31'), ObjectId('679193a47fd85c8616659c32'), ObjectId('679193a47fd85c8616659c33'), ObjectId('679193a47fd85c8616659c34'), ObjectId('679193a47fd85c8616659c35'), ObjectId('679193a47fd85c8616659c36'), ObjectId('679193a47fd85c8616659c37'), ObjectId('679193a47fd85c8616659c38'), ObjectId('679193a47fd85c8616659c39'), ObjectId('679193a47fd85c8616659c3a'), ObjectId('679193a47fd85c8616659c3b'), ObjectId('679193a47fd85c8616659c3c'), ObjectId('679193a47fd85c8616659c3d'), ObjectId('679193a47fd85c8616659c3e'), ObjectId('679193a47fd85c8616659c3f'), ObjectId('679193a47fd85c8616659c40'), ObjectId('679193a47fd85c8616659c41')], acknowledged=True)

In [ ]:
fs = InsecureClient('http://bdata.iptime.org:9999', user='hadoop')
path = '/user/hadoop/sports/'
# 생활체육 참여율
f_name = '규칙적_체육활동_참여율_주_1회_이상__연도별_비교_20250114092534.csv'
with fs.read(f'{path}{f_name}', encoding='euc-kr') as reader:
    df2 = pd.read_csv(reader)

# 컬렉션(테이블) 연결/만들기
collection2 = db.get_collection('rate_csv')
# DateFrame 형식의 데이터 입력
collection2.insert_many(df2.to_dict(orient='records'))
print('컬렉션에 데이터 입력 완료')

In [41]:
# 입력된 데이터 전체 확인
result = collection.find({},{'_id':0})
for row in result:
    print(row)

{'시점': 2001, '대한민국': 4.7, '중국': 8.3, '일본': 0.4, '미국': 1.0, '브라질': 1.4, '페루': 0.6, '핀란드': 2.6, '프랑스': 2.0, '독일': 1.7, '스웨덴': 1.4, '영국': 2.6, '남아프리카공화국': 2.7, '오스트레일리아': 2.0}
{'시점': 2002, '대한민국': 7.7, '중국': 9.1, '일본': 0.0, '미국': 1.7, '브라질': 3.1, '페루': 5.5, '핀란드': 1.7, '프랑스': 1.1, '독일': -0.2, '스웨덴': 2.2, '영국': 1.8, '남아프리카공화국': 3.7, '오스트레일리아': 4.0}
{'시점': 2003, '대한민국': 3.1, '중국': 10.0, '일본': 1.5, '미국': 2.8, '브라질': 1.1, '페루': 4.2, '핀란드': 2.0, '프랑스': 0.8, '독일': -0.7, '스웨덴': 2.3, '영국': 3.1, '남아프리카공화국': 2.9, '오스트레일리아': 3.1}
{'시점': 2004, '대한민국': 5.2, '중국': 10.1, '일본': 2.2, '미국': 3.8, '브라질': 5.8, '페루': 5.0, '핀란드': 4.0, '프랑스': 2.8, '독일': 1.2, '스웨덴': 4.3, '영국': 2.4, '남아프리카공화국': 4.6, '오스트레일리아': 4.2}
{'시점': 2005, '대한민국': 4.4, '중국': 11.4, '일본': 1.8, '미국': 3.5, '브라질': 3.2, '페루': 6.3, '핀란드': 2.8, '프랑스': 1.7, '독일': 0.7, '스웨덴': 2.9, '영국': 2.7, '남아프리카공화국': 5.3, '오스트레일리아': 3.2}
{'시점': 2006, '대한민국': 5.2, '중국': 12.7, '일본': 1.4, '미국': 2.8, '브라질': 4.0, '페루': 7.5, '핀란드': 4.0, '프랑스': 2.4, '독일': 3.8, '스웨덴': 4.7, '영국': 2.4, '남아프리카공화국': 5.6, '오스트레일리아': 2.8}
{'시점': 2007, '대한민국': 5.8, '중국': 14.2, '일본': 1.5, '미국': 2.0, '브라질': 6.1, '페루': 8.5, '핀란드': 5.3, '프랑스': 2.4, '독일': 3.0, '스웨덴': 3.4, '영국': 2.6, '남아프리카공화국': 5.4, '오스트레일리아': 3.8}
{'시점': 2008, '대한민국': 3.0, '중국': 9.7, '일본': -1.2, '미국': 0.1, '브라질': 5.1, '페루': 9.1, '핀란드': 0.8, '프랑스': 0.3, '독일': 1.0, '스웨덴': -0.5, '영국': -0.2, '남아프리카공화국': 3.2, '오스트레일리아': 3.6}
{'시점': 2009, '대한민국': 0.8, '중국': 9.4, '일본': -5.7, '미국': -2.6, '브라질': -0.1, '페루': 1.1, '핀란드': -8.1, '프랑스': -2.9, '독일': -5.7, '스웨덴': -4.3, '영국': -4.6, '남아프리카공화국': -1.5, '오스트레일리아': 1.9}
{'시점': 2010, '대한민국': 7.0, '중국': 10.6, '일본': 4.1, '미국': 2.7, '브라질': 7.5, '페루': 8.3, '핀란드': 3.2, '프랑스': 1.9, '독일': 4.2, '스웨덴': 6.0, '영국': 2.2, '남아프리카공화국': 3.0, '오스트레일리아': 2.2}
{'시점': 2011, '대한민국': 3.7, '중국': 9.6, '일본': 0.0, '미국': 1.6, '브라질': 4.0, '페루': 6.3, '핀란드': 2.5, '프랑스': 2.2, '독일': 3.9, '스웨덴': 3.2, '영국': 1.1, '남아프리카공화국': 3.2, '오스트레일리아': 2.4}
{'시점': 2012, '대한민국': 2.5, '중국': 7.9, '일본': 1.4, '미국': 2.3, '브라질': 1.9, '페루': 6.1, '핀란드': -1.4, '프랑스': 0.3, '독일': 0.4, '스웨덴': -0.6, '영국': 1.5, '남아프리카공화국': 2.4, '오스트레일리아': 3.9}
{'시점': 2013, '대한민국': 3.3, '중국': 7.8, '일본': 2.0, '미국': 2.1, '브라질': 3.0, '페루': 5.9, '핀란드': -0.9, '프랑스': 0.6, '독일': 0.4, '스웨덴': 1.2, '영국': 1.8, '남아프리카공화국': 2.5, '오스트레일리아': 2.6}
{'시점': 2014, '대한민국': 3.2, '중국': 7.4, '일본': 0.3, '미국': 2.5, '브라질': 0.5, '페루': 2.4, '핀란드': -0.4, '프랑스': 1.0, '독일': 2.2, '스웨덴': 2.7, '영국': 3.2, '남아프리카공화국': 1.4, '오스트레일리아': 2.6}
{'시점': 2015, '대한민국': 2.9, '중국': 7.0, '일본': 1.6, '미국': 2.9, '브라질': -3.5, '페루': 3.3, '핀란드': 0.5, '프랑스': 1.1, '독일': 1.5, '스웨덴': 4.5, '영국': 2.2, '남아프리카공화국': 1.3, '오스트레일리아': 2.2}
{'시점': 2016, '대한민국': 3.2, '중국': 6.8, '일본': 0.8, '미국': 1.8, '브라질': -3.3, '페루': 4.0, '핀란드': 2.8, '프랑스': 1.1, '독일': 2.2, '스웨덴': 2.1, '영국': 1.9, '남아프리카공화국': 0.7, '오스트레일리아': 2.8}
{'시점': 2017, '대한민국': 3.4, '중국': 6.9, '일본': 1.7, '미국': 2.5, '브라질': 1.3, '페루': 2.5, '핀란드': 3.2, '프랑스': 2.3, '독일': 2.7, '스웨덴': 2.6, '영국': 2.7, '남아프리카공화국': 1.2, '오스트레일리아': 2.3}
{'시점': 2018, '대한민국': 3.2, '중국': 6.7, '일본': 0.6, '미국': 3.0, '브라질': 1.8, '페루': 4.0, '핀란드': 1.1, '프랑스': 1.9, '독일': 1.0, '스웨덴': 2.0, '영국': 1.4, '남아프리카공화국': 1.6, '오스트레일리아': 2.9}
{'시점': 2019, '대한민국': 2.3, '중국': 6.0, '일본': -0.4, '미국': 2.5, '브라질': 1.2, '페루': 2.2, '핀란드': 1.2, '프랑스': 1.8, '독일': 1.1, '스웨덴': 2.0, '영국': 1.6, '남아프리카공화국': 0.3, '오스트레일리아': 2.2}
{'시점': 2020, '대한민국': -0.7, '중국': 2.2, '일본': -4.1, '미국': -2.2, '브라질': -3.3, '페루': -10.9, '핀란드': -2.4, '프랑스': -7.5, '독일': -3.8, '스웨덴': -2.2, '영국': -10.4, '남아프리카공화국': -6.0, '오스트레일리아': -0.3}
{'시점': 2021, '대한민국': 4.6, '중국': 8.4, '일본': 2.6, '미국': 5.8, '브라질': 4.8, '페루': 13.4, '핀란드': 2.8, '프랑스': 6.4, '독일': 3.2, '스웨덴': 6.1, '영국': 8.7, '남아프리카공화국': 4.7, '오스트레일리아': 2.1}
{'시점': 2022, '대한민국': 2.7, '중국': 3.0, '일본': 1.0, '미국': 1.9, '브라질': 3.0, '페루': 2.7, '핀란드': 1.3, '프랑스': 2.5, '독일': 1.8, '스웨덴': 2.7, '영국': 4.3, '남아프리카공화국': 1.9, '오스트레일리아': 4.3}
{'시점': 2023, '대한민국': 1.4, '중국': 5.2, '일본': 1.9, '미국': 2.5, '브라질': 2.9, '페루': -0.6, '핀란드': -1.0, '프랑스': 0.7, '독일': -0.3, '스웨덴': -0.2, '영국': 0.1, '남아프리카공화국': 0.6, '오스트레일리아': 3.0}

In [26]:
# 입력된 데이터 전체 확인
result = collection.find()
# collection.find()
print(type(result)) 
print(result)
for row in result:
    print(row)

<class 'pymongo.synchronous.cursor.Cursor'>
<pymongo.synchronous.cursor.Cursor object at 0x0000026D96C2AFD0>
{'_id': ObjectId('6790a21b0c883b54957c3381'), '시점': 2001, '대한민국': 4.7, '중국': 8.3, '일본': 0.4, '미국': 1.0, '브라질': 1.4, '페루': 0.6, '핀란드': 2.6, '프랑스': 2.0, '독일': 1.7, '스웨덴': 1.4, '영국': 2.6, '남아프리카공화국': 2.7, '오스트레일리아': 2.0}
{'_id': ObjectId('6790a21b0c883b54957c3382'), '시점': 2002, '대한민국': 7.7, '중국': 9.1, '일본': 0.0, '미국': 1.7, '브라질': 3.1, '페루': 5.5, '핀란드': 1.7, '프랑스': 1.1, '독일': -0.2, '스웨덴': 2.2, '영국': 1.8, '남아프리카공화국': 3.7, '오스트레일리아': 4.0}
{'_id': ObjectId('6790a21b0c883b54957c3383'), '시점': 2003, '대한민국': 3.1, '중국': 10.0, '일본': 1.5, '미국': 2.8, '브라질': 1.1, '페루': 4.2, '핀란드': 2.0, '프랑스': 0.8, '독일': -0.7, '스웨덴': 2.3, '영국': 3.1, '남아프리카공화국': 2.9, '오스트레일리아': 3.1}
{'_id': ObjectId('6790a21b0c883b54957c3384'), '시점': 2004, '대한민국': 5.2, '중국': 10.1, '일본': 2.2, '미국': 3.8, '브라질': 5.8, '페루': 5.0, '핀란드': 4.0, '프랑스': 2.8, '독일': 1.2, '스웨덴': 4.3, '영국': 2.4, '남아프리카공화국': 4.6, '오스트레일리아': 4.2}
{'_id': ObjectId('6790a21b0c883b54957c3385'), '시점': 2005, '대한민국': 4.4, '중국': 11.4, '일본': 1.8, '미국': 3.5, '브라질': 3.2, '페루': 6.3, '핀란드': 2.8, '프랑스': 1.7, '독일': 0.7, '스웨덴': 2.9, '영국': 2.7, '남아프리카공화국': 5.3, '오스트레일리아': 3.2}
{'_id': ObjectId('6790a21b0c883b54957c3386'), '시점': 2006, '대한민국': 5.2, '중국': 12.7, '일본': 1.4, '미국': 2.8, '브라질': 4.0, '페루': 7.5, '핀란드': 4.0, '프랑스': 2.4, '독일': 3.8, '스웨덴': 4.7, '영국': 2.4, '남아프리카공화국': 5.6, '오스트레일리아': 2.8}
{'_id': ObjectId('6790a21b0c883b54957c3387'), '시점': 2007, '대한민국': 5.8, '중국': 14.2, '일본': 1.5, '미국': 2.0, '브라질': 6.1, '페루': 8.5, '핀란드': 5.3, '프랑스': 2.4, '독일': 3.0, '스웨덴': 3.4, '영국': 2.6, '남아프리카공화국': 5.4, '오스트레일리아': 3.8}
{'_id': ObjectId('6790a21b0c883b54957c3388'), '시점': 2008, '대한민국': 3.0, '중국': 9.7, '일본': -1.2, '미국': 0.1, '브라질': 5.1, '페루': 9.1, '핀란드': 0.8, '프랑스': 0.3, '독일': 1.0, '스웨덴': -0.5, '영국': -0.2, '남아프리카공화국': 3.2, '오스트레일리아': 3.6}
{'_id': ObjectId('6790a21b0c883b54957c3389'), '시점': 2009, '대한민국': 0.8, '중국': 9.4, '일본': -5.7, '미국': -2.6, '브라질': -0.1, '페루': 1.1, '핀란드': -8.1, '프랑스': -2.9, '독일': -5.7, '스웨덴': -4.3, '영국': -4.6, '남아프리카공화국': -1.5, '오스트레일리아': 1.9}
{'_id': ObjectId('6790a21b0c883b54957c338a'), '시점': 2010, '대한민국': 7.0, '중국': 10.6, '일본': 4.1, '미국': 2.7, '브라질': 7.5, '페루': 8.3, '핀란드': 3.2, '프랑스': 1.9, '독일': 4.2, '스웨덴': 6.0, '영국': 2.2, '남아프리카공화국': 3.0, '오스트레일리아': 2.2}
{'_id': ObjectId('6790a21b0c883b54957c338b'), '시점': 2011, '대한민국': 3.7, '중국': 9.6, '일본': 0.0, '미국': 1.6, '브라질': 4.0, '페루': 6.3, '핀란드': 2.5, '프랑스': 2.2, '독일': 3.9, '스웨덴': 3.2, '영국': 1.1, '남아프리카공화국': 3.2, '오스트레일리아': 2.4}
{'_id': ObjectId('6790a21b0c883b54957c338c'), '시점': 2012, '대한민국': 2.5, '중국': 7.9, '일본': 1.4, '미국': 2.3, '브라질': 1.9, '페루': 6.1, '핀란드': -1.4, '프랑스': 0.3, '독일': 0.4, '스웨덴': -0.6, '영국': 1.5, '남아프리카공화국': 2.4, '오스트레일리아': 3.9}
{'_id': ObjectId('6790a21b0c883b54957c338d'), '시점': 2013, '대한민국': 3.3, '중국': 7.8, '일본': 2.0, '미국': 2.1, '브라질': 3.0, '페루': 5.9, '핀란드': -0.9, '프랑스': 0.6, '독일': 0.4, '스웨덴': 1.2, '영국': 1.8, '남아프리카공화국': 2.5, '오스트레일리아': 2.6}
{'_id': ObjectId('6790a21b0c883b54957c338e'), '시점': 2014, '대한민국': 3.2, '중국': 7.4, '일본': 0.3, '미국': 2.5, '브라질': 0.5, '페루': 2.4, '핀란드': -0.4, '프랑스': 1.0, '독일': 2.2, '스웨덴': 2.7, '영국': 3.2, '남아프리카공화국': 1.4, '오스트레일리아': 2.6}
{'_id': ObjectId('6790a21b0c883b54957c338f'), '시점': 2015, '대한민국': 2.9, '중국': 7.0, '일본': 1.6, '미국': 2.9, '브라질': -3.5, '페루': 3.3, '핀란드': 0.5, '프랑스': 1.1, '독일': 1.5, '스웨덴': 4.5, '영국': 2.2, '남아프리카공화국': 1.3, '오스트레일리아': 2.2}
{'_id': ObjectId('6790a21b0c883b54957c3390'), '시점': 2016, '대한민국': 3.2, '중국': 6.8, '일본': 0.8, '미국': 1.8, '브라질': -3.3, '페루': 4.0, '핀란드': 2.8, '프랑스': 1.1, '독일': 2.2, '스웨덴': 2.1, '영국': 1.9, '남아프리카공화국': 0.7, '오스트레일리아': 2.8}
{'_id': ObjectId('6790a21b0c883b54957c3391'), '시점': 2017, '대한민국': 3.4, '중국': 6.9, '일본': 1.7, '미국': 2.5, '브라질': 1.3, '페루': 2.5, '핀란드': 3.2, '프랑스': 2.3, '독일': 2.7, '스웨덴': 2.6, '영국': 2.7, '남아프리카공화국': 1.2, '오스트레일리아': 2.3}
{'_id': ObjectId('6790a21b0c883b54957c3392'), '시점': 2018, '대한민국': 3.2, '중국': 6.7, '일본': 0.6, '미국': 3.0, '브라질': 1.8, '페루': 4.0, '핀란드': 1.1, '프랑스': 1.9, '독일': 1.0, '스웨덴': 2.0, '영국': 1.4, '남아프리카공화국': 1.6, '오스트레일리아': 2.9}
{'_id': ObjectId('6790a21b0c883b54957c3393'), '시점': 2019, '대한민국': 2.3, '중국': 6.0, '일본': -0.4, '미국': 2.5, '브라질': 1.2, '페루': 2.2, '핀란드': 1.2, '프랑스': 1.8, '독일': 1.1, '스웨덴': 2.0, '영국': 1.6, '남아프리카공화국': 0.3, '오스트레일리아': 2.2}
{'_id': ObjectId('6790a21b0c883b54957c3394'), '시점': 2020, '대한민국': -0.7, '중국': 2.2, '일본': -4.1, '미국': -2.2, '브라질': -3.3, '페루': -10.9, '핀란드': -2.4, '프랑스': -7.5, '독일': -3.8, '스웨덴': -2.2, '영국': -10.4, '남아프리카공화국': -6.0, '오스트레일리아': -0.3}
{'_id': ObjectId('6790a21b0c883b54957c3395'), '시점': 2021, '대한민국': 4.6, '중국': 8.4, '일본': 2.6, '미국': 5.8, '브라질': 4.8, '페루': 13.4, '핀란드': 2.8, '프랑스': 6.4, '독일': 3.2, '스웨덴': 6.1, '영국': 8.7, '남아프리카공화국': 4.7, '오스트레일리아': 2.1}
{'_id': ObjectId('6790a21b0c883b54957c3396'), '시점': 2022, '대한민국': 2.7, '중국': 3.0, '일본': 1.0, '미국': 1.9, '브라질': 3.0, '페루': 2.7, '핀란드': 1.3, '프랑스': 2.5, '독일': 1.8, '스웨덴': 2.7, '영국': 4.3, '남아프리카공화국': 1.9, '오스트레일리아': 4.3}
{'_id': ObjectId('6790a21b0c883b54957c3397'), '시점': 2023, '대한민국': 1.4, '중국': 5.2, '일본': 1.9, '미국': 2.5, '브라질': 2.9, '페루': -0.6, '핀란드': -1.0, '프랑스': 0.7, '독일': -0.3, '스웨덴': -0.2, '영국': 0.1, '남아프리카공화국': 0.6, '오스트레일리아': 3.0}

#  $eq  (equals) 주어진 값과 일치하는 값 
#  $gt  (greater than) 주어진 값보다 큰 값 
#  $gte  (greater than or equals) 주어진 값보다 크거나 같은 값 
#  $lt  (less than) 주어진 값보다 작은 값 
#  $lte  (less then or equals) 주어진 값보다 작거나 같은 값 
#  $ne  (not equlas) 주어진 값과 일치하지 않는 값 
#  $in  (in) 주어진 배열 안에 속하는 값
#  $nin  (not in) 주어진 배열 안에 속하지 않는 값 

# age필드의 값이 10보다 크고 30보다 작은 값 조회
data1 = collection.find({'age' : {'$gt':10, '$lt':34}},{'_id':0}) #가져오기
for i in data1:
    print(i)

# id가 pyaa 이고 나이가 33인 것 출력
data1 = collection.find({'$and' : [{'id':'pyaa'}, {'age':33}]},{'_id':0}) #가져오기
for i in data1:
    print(i)

In [44]:
# 조건식으로 데이터 확인
result2 = collection.find({'$and': [ {'일본': {'$lt':1}}, {'시점': {'$lte':2018}} ]}, {'_id':0, '대한민국':0}) # 조건식으로 가져오기
for row in result2:
    print(row)

{'시점': 2001, '중국': 8.3, '일본': 0.4, '미국': 1.0, '브라질': 1.4, '페루': 0.6, '핀란드': 2.6, '프랑스': 2.0, '독일': 1.7, '스웨덴': 1.4, '영국': 2.6, '남아프리카공화국': 2.7, '오스트레일리아': 2.0}
{'시점': 2002, '중국': 9.1, '일본': 0.0, '미국': 1.7, '브라질': 3.1, '페루': 5.5, '핀란드': 1.7, '프랑스': 1.1, '독일': -0.2, '스웨덴': 2.2, '영국': 1.8, '남아프리카공화국': 3.7, '오스트레일리아': 4.0}
{'시점': 2008, '중국': 9.7, '일본': -1.2, '미국': 0.1, '브라질': 5.1, '페루': 9.1, '핀란드': 0.8, '프랑스': 0.3, '독일': 1.0, '스웨덴': -0.5, '영국': -0.2, '남아프리카공화국': 3.2, '오스트레일리아': 3.6}
{'시점': 2009, '중국': 9.4, '일본': -5.7, '미국': -2.6, '브라질': -0.1, '페루': 1.1, '핀란드': -8.1, '프랑스': -2.9, '독일': -5.7, '스웨덴': -4.3, '영국': -4.6, '남아프리카공화국': -1.5, '오스트레일리아': 1.9}
{'시점': 2011, '중국': 9.6, '일본': 0.0, '미국': 1.6, '브라질': 4.0, '페루': 6.3, '핀란드': 2.5, '프랑스': 2.2, '독일': 3.9, '스웨덴': 3.2, '영국': 1.1, '남아프리카공화국': 3.2, '오스트레일리아': 2.4}
{'시점': 2014, '중국': 7.4, '일본': 0.3, '미국': 2.5, '브라질': 0.5, '페루': 2.4, '핀란드': -0.4, '프랑스': 1.0, '독일': 2.2, '스웨덴': 2.7, '영국': 3.2, '남아프리카공화국': 1.4, '오스트레일리아': 2.6}
{'시점': 2016, '중국': 6.8, '일본': 0.8, '미국': 1.8, '브라질': -3.3, '페루': 4.0, '핀란드': 2.8, '프랑스': 1.1, '독일': 2.2, '스웨덴': 2.1, '영국': 1.9, '남아프리카공화국': 0.7, '오스트레일리아': 2.8}
{'시점': 2018, '중국': 6.7, '일본': 0.6, '미국': 3.0, '브라질': 1.8, '페루': 4.0, '핀란드': 1.1, '프랑스': 1.9, '독일': 1.0, '스웨덴': 2.0, '영국': 1.4, '남아프리카공화국': 1.6, '오스트레일리아': 2.9}